### ISSUE TITLE
Proposal: New API to return Exit Code

### ISSUE THREAD

**Issue by nogic1008** [Cysharp/MicroBatchFramework#17]
I'm replacing a TRADITIONAL batch program with this Framework.
However, sadly, these OLD programs are linked to other systems by their exit codes.
So I need new API to return an exit code in this framework.

Something like this.
```csharp
class Program
{
    static Task<int> Main(string[] args)
        => await BatchHost.CreateDefaultBuilder().RunBatchEngineWithExitCodeAsync<SampleBatch>(args);
}

class SampleBatch : BatchBase
{
    [Command("sync")]
    public int ParseInt(string source) => int.TryParse(source, out var i) ? i : -1;

    [Command("async")]
    public async Task<int> ParseIntAsync(string source)
    {
        Context.Logger.LogInformation("Wait...");
        await Task.Delay(1000);
        return ParseInt(source);
    }
}
```

**Comment by neuecc** [comment]
thank you for the request.
I've released `1.5.0`, it includes this feature.
If returns `int` or `Task<int>`, set ExitCode as there return value.
